apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana.github.io.yaml
  - kube-prometheus-stack.yaml
  - logs-dashboard.yaml
  - loki.yaml
  - loki-datasource.yaml
  - metrics-dashboard.yaml
  - prometheus-datasource.yaml