apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: bitnamicharts/keycloak
      version: '24.0.1'
      sourceRef:
        kind: HelmRepository
        name: dockerhub
        namespace: flux-system
  install:
    createNamespace: true
  releaseName: keycloak
  targetNamespace: keycloak
  storageNamespace: keycloak
  values:
    resources:
      requests:
        cpu: 10m
        memory: 1Gi
      limits:
        memory: 1Gi
    fullnameOverride: keycloak
    production: true
    proxy: edge
    ingress:
      enabled: true
      tls: true
      ingressClassName: "nginx"
      hostname: ${KEYCLOAK_HOSTNAME}
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      extraHosts:
        - name: ${KEYCLOAK_HOSTNAME}
          path: /
      extraTls:
        - secretName: ${KEYCLOAK_HOSTNAME}
          hosts:
            - ${KEYCLOAK_HOSTNAME}
    auth:
      adminUser: ${KEYCLOAK_USERNAME}
      adminPassword: ${KEYCLOAK_PASSWORD}
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: false
#    externalDatabase:
#      host: "postgresql"
#      port: 5432
#      database: keycloak
#      existingSecret: "keycloak.postgresql.credentials.postgresql.acid.zalan.do"
#      existingSecretUserKey: "username"
#      existingSecretPasswordKey: "password"
