apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana/helm-charts/grafana-operator
      version: v5.10.0
      sourceRef:
        kind: HelmRepository
        name: ghcr.io
        namespace: flux-system
  install:
    createNamespace: true
  releaseName: grafana-operator
  targetNamespace: grafana-operator
  storageNamespace: grafana-operator