apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  dependsOn:
    - name: cert-manager
  chart:
    spec:
      chart: cluster-api-operator
      version: '0.14.0'
      sourceRef:
        kind: HelmRepository
        name: capi-operator
      interval: 5m
  install:
    createNamespace: true
  targetNamespace: capi-operator-system
  storageNamespace: capi-operator-system
  releaseName: capi-operator
