apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kustomizations
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux2-sync
#  healthChecks:
#    - apiVersion: helm.toolkit.fluxcd.io/v2
#      kind: HelmRelease
#      name: cert-manager
#      namespace: flux-system
