apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperlessngx.fullname" . }}-credentials
  labels:
    {{- include "paperlessngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
stringData:
  PAPERLESS_ADMIN_USER: {{ .Values.paperless.adminUser | quote }}
  PAPERLESS_ADMIN_PASSWORD: {{ (.Values.paperless.adminPassword | default (randAlphaNum 20) ) | quote }}
  PAPERLESS_EMAIL_HOST_USER: {{ .Values.email.user | quote }}
  PAPERLESS_EMAIL_HOST_PASSWORD: {{ .Values.email.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperlessngx.fullname" . }}-restic-credentials
  labels:
    {{- include "paperlessngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
stringData:
  RESTIC_PASSWORD: {{ .Values.backup.password | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.backup.accesskeyid | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backup.secretAccessKey | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperlessngx.fullname" . }}-restic-config
  labels:
    {{- include "paperlessngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  RESTIC_REPOSITORY: {{ .Values.backup.repository | quote }}
  TZ: "Etc/UTC"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperlessngx.fullname" . }}-config
  labels:
    {{- include "paperlessngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  PAPERLESS_DB_HOST: "postgresql-hl"
  PAPERLESS_FILENAME_FORMAT: '{created}-{original_name}'
  PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: "True"
  PAPERLESS_REDIS: "redis://:paperless@redis-master:6379"
  PAPERLESS_SECRET_KEY: {{ randAlphaNum 128 | quote }}
  PAPERLESS_EMAIL_HOST: {{ .Values.email.host | quote }}
  PAPERLESS_EMAIL_PORT: {{ .Values.email.port | quote }}
  PAPERLESS_EMAIL_FROM: {{ .Values.email.user | quote }}
  PAPERLESS_EMAIL_USE_TLS: "true"
  PAPERLESS_EMAIL_USE_SSL: "true"
  PAPERLESS_EXPORT_CRON: "0-30/30 * * * *"
{{- if .Values.ingress.enabled }}
{{- $host := index .Values.ingress.hosts 0 }}
  PAPERLESS_URL: "http{{ if $.Values.ingress.tls }}s{{ end }}://{{ $host.host }}"
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperlessngx.fullname" . }}-backup
  labels:
    {{- include "paperlessngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  backup.cron: "0-55/10 * * * * document_exporter /usr/src/paperless/export"
