apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: bitnamicharts/external-dns
      # TODO: magicvar(version)
      version: '7.1.2'
      sourceRef:
        kind: HelmRepository
        name: dockerhub
      interval: 5m
  install:
    createNamespace: true
  targetNamespace: ingress
  storageNamespace: ingress
  releaseName: external-dns
  values:
    resources:
      requests:
        cpu: 1m
        memory: 50Mi
      limits:
        memory: 50Mi
    provider: cloudflare
    # TODO: magicvar(config)
    txtOwnerId: ${EXTERNAL_DNS_TXTOWNERID}
    cloudflare:
      # TODO: magicvar(secret)
      apiToken: ${EXTERNAL_DNS_CF_TOKEN}
      proxied: false