apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 5m
  # TODO: magicvar(repo)
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      # TODO: magicvar(version)
      version: '1.16.1'
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 5m
  install:
    createNamespace: true
  targetNamespace: ingress
  storageNamespace: ingress
  releaseName: cert-manager
  values:
    fullnameOverride: cert-manager
    crds:
      enabled: true
    podDnsPolicy: "None"
    podDnsConfig:
       nameservers:
         - "1.1.1.1"
         - "9.9.9.9"
    extraArgs:
      - --acme-http01-solver-nameservers=1.1.1.1:53,9.9.9.9:53
    resources:
      limits:
        cpu: 300m
        memory: 100Mi
      requests:
        cpu: 300m
        memory: 100Mi
    cainjector:
      resources:
        limits:
          cpu: 10m
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 100Mi
    webhook:
      resources:
        limits:
          cpu: 10m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 50Mi
